language: node_js

# Use trusty
sudo: true
dist: trusty

# Don't build commits in the queue if a new commit arrives
git:
  depth: 1

# node versions to test
node_js:
  - "5"  # Minimum version
  - "6"  # Latest version

# If any version fails, cancel the others
matrix:
  fast_finish: true

before_script:
  - npm install -g gulp-cli

script: gulp
